ALTER SESSION SET CONTAINER=TRAFFIC_SIMULATOR;
CREATE USER MOH_WORKFLOW_SCHEMA IDENTIFIED BY password;
GRANT CONNECT, RESOURCE TO MOH_WORKFLOW_SCHEMA;
ALTER USER MOH_WORKFLOW_SCHEMA QUOTA UNLIMITED ON SYSTEM;
exit;
