--------------------------------------------------------
--  DDL for Table BONES_REVEAL
--------------------------------------------------------

  CREATE TABLE "MOH_WORKFLOW_SCHEMA"."BONES_REVEAL" 
   (	"BONES_REVEAL_ID" NUMBER NOT NULL ,
	"DISABILITY_ID"  NUMBER,
	"RESULT"	VARCHAR2(255 BYTE),
	"DESCRIPTION"	VARCHAR2(255 BYTE),
	"REVEAL_DONE"	NUMBER(1,0),
	"REQUEST_ID"	NUMBER NOT NULL
   );
CREATE UNIQUE INDEX "MOH_WORKFLOW_SCHEMA"."BONES_REVEAL_PK" ON "MOH_WORKFLOW_SCHEMA"."BONES_REVEAL" ("BONES_REVEAL_ID");
ALTER TABLE "MOH_WORKFLOW_SCHEMA"."BONES_REVEAL" ADD CONSTRAINT "BONES_REVEAL_PK" PRIMARY KEY ("BONES_REVEAL_ID")
 ALTER TABLE "MOH_WORKFLOW_SCHEMA"."EYE_REVEAL" MODIFY "RESULT" NULL;
=============================================================================
Change Date: 22-07-2019
-----------------------
-- this change is to make Citizen and Request is related to Zone
ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CITIZEN" ADD zone_id number ;
UPDATE  "MOH_WORKFLOW_SCHEMA"."CITIZEN" SET ZONE_ID = 1;
ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CITIZEN" MODIFY ("ZONE_ID" NOT NULL ENABLE);
ALTER TABLE "MOH_WORKFLOW_SCHEMA"."CITIZEN" ADD CONSTRAINT "CITIZEN_FK4" FOREIGN KEY ("ZONE_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."ZONE" ("ZONE_ID") ENABLE;

ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST" ADD zone_id number ;
UPDATE  "MOH_WORKFLOW_SCHEMA"."REQUEST" SET ZONE_ID = 1;
ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST" MODIFY ("ZONE_ID" NOT NULL ENABLE);
ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST" ADD CONSTRAINT "REQUEST_FK7" FOREIGN KEY ("ZONE_ID")
	  REFERENCES "MOH_WORKFLOW_SCHEMA"."ZONE" ("ZONE_ID") ENABLE;


Change Date: 27-07-2019
-----------------------

ALTER TABLE "MOH_WORKFLOW_SCHEMA"."SYSTEM_AUDIT" ADD ZONE_ID number ;
UPDATE  "MOH_WORKFLOW_SCHEMA"."SYSTEM_AUDIT" SET ZONE_ID = 1;
ALTER TABLE "MOH_WORKFLOW_SCHEMA"."SYSTEM_AUDIT" MODIFY ("ZONE_ID" NOT NULL ENABLE);