CREATE SEQUENCE  "MOH_WORKFLOW_SCHEMA"."SEQ_REQUEST_PAYMENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

-- the following statement is already update in constrain.sql
ALTER TABLE "MOH_WORKFLOW_SCHEMA"."SYSTEM_USER" DROP CONSTRAINT SYSTEM_USER_UK1;

ALTER TABLE "MOH_WORKFLOW_SCHEMA"."DOCUMENT_TYPE" ADD  category VARCHAR2(100 BYTE) ;
ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_DOCUMENT" MODIFY TYPE number ;
ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_DOCUMENT" RENAME COLUMN TYPE TO DOCUMENT_TYPE_ID;
ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_DOCUMENT" ADD CONSTRAINT "REQUEST_DOCUMENT_FK2" FOREIGN KEY ("DOCUMENT_TYPE_ID")  REFERENCES "MOH_WORKFLOW_SCHEMA"."DOCUMENT_TYPE" ("DOCUMENT_TYPE_ID") ENABLE;
ALTER TABLE "MOH_WORKFLOW_SCHEMA"."REQUEST_DOCUMENT" ADD CONSTRAINT REQUEST_DOCUMENT_UK1 UNIQUE (DOCUMENT_TYPE_ID, REQUEST_ID);
CREATE SEQUENCE  "MOH_WORKFLOW_SCHEMA"."SEQ_BONES_REVEAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "MOH_WORKFLOW_SCHEMA"."SEQ_EYE_REVEAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


