ALTER SESSION SET CONTAINER=TRAFFIC_SIMULATOR;
CREATE USER SCHEDULER_SCHEMA IDENTIFIED BY scheduler_12345;
GRANT CONNECT, RESOURCE TO SCHEDULER_SCHEMA;
ALTER USER SCHEDULER_SCHEMA QUOTA UNLIMITED ON SYSTEM;
exit;
