--------------------------------------------------------
--  File created - Wednesday-March-20-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACTIVE_DIRECTORY
--------------------------------------------------------
CONNECT TRAFFIC_SIMULATOR_SCHEMA/ts_12345@//localhost:1521/TRAFFIC_SIMULATOR;
  CREATE TABLE "TRAFFIC_SIMULATOR_SCHEMA"."ACTIVE_DIRECTORY" 
   (	"ID" NUMBER(10,0), 
	"SECURITY_PRINCIPAL" VARCHAR2(1000 BYTE), 
	"SECURITY_CREDENTIALS" VARCHAR2(1000 BYTE), 
	"SECURITY_AUTHENTICATION" VARCHAR2(1000 BYTE), 
	"PROVIDER_URL" VARCHAR2(255 BYTE), 
	"DOMAIN" VARCHAR2(200 BYTE), 
	"ACTIVE" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADMINS
--------------------------------------------------------

  CREATE TABLE "TRAFFIC_SIMULATOR_SCHEMA"."ADMINS" 
   (	"USERNAME" VARCHAR2(45 BYTE), 
	"LDAP" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ANNOUNCEMENT
--------------------------------------------------------

  CREATE TABLE "TRAFFIC_SIMULATOR_SCHEMA"."ANNOUNCEMENT" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(45 BYTE), 
	"PATH" VARCHAR2(45 BYTE), 
	"ENABLED" NUMBER(3,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CCN
--------------------------------------------------------

  CREATE TABLE "TRAFFIC_SIMULATOR_SCHEMA"."CCN" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(45 BYTE), 
	"PC" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"ENABLED" NUMBER(3,0) DEFAULT 1, 
	"DEFAULTVALUE" NUMBER(3,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COUNTRIES
--------------------------------------------------------

  CREATE TABLE "TRAFFIC_SIMULATOR_SCHEMA"."COUNTRIES" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(45 BYTE), 
	"DESCRIPTION" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"ENABLED" NUMBER(3,0) DEFAULT 1, 
	"MNC" VARCHAR2(20 BYTE), 
	"MCC" VARCHAR2(20 BYTE), 
	"DIAL_CODE" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"DEFAULTVALUE" NUMBER(3,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENGINE_CONFIGURATION
--------------------------------------------------------

  CREATE TABLE "TRAFFIC_SIMULATOR_SCHEMA"."ENGINE_CONFIGURATION" 
   (	"PC" NUMBER(10,0), 
	"SSN" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOCATION_NUMBERS
--------------------------------------------------------

  CREATE TABLE "TRAFFIC_SIMULATOR_SCHEMA"."LOCATION_NUMBERS" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(45 BYTE), 
	"VALUE" VARCHAR2(45 BYTE), 
	"DESCRIPTION" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"ENABLED" NUMBER(3,0) DEFAULT 1, 
	"DEFAULTVALUE" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NODES
--------------------------------------------------------

  CREATE TABLE "TRAFFIC_SIMULATOR_SCHEMA"."NODES" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(45 BYTE), 
	"DESCRIPTION" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SCENARIOS
--------------------------------------------------------

  CREATE TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SCENARIOS" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(45 BYTE), 
	"SCXMLDOC_O" VARCHAR2(225 BYTE), 
	"DESCRIPTION" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"HASCOUNTRY" NUMBER(3,0) DEFAULT '1', 
	"HASTRAFFICMODE" NUMBER(3,0) DEFAULT '1', 
	"HASLOCATIONNUMBERS" NUMBER(3,0) DEFAULT '1', 
	"HASDURATION" NUMBER(3,0) DEFAULT '1', 
	"SERVICEKEY_O" NUMBER(10,0), 
	"SERVICEKEY_T" NUMBER(10,0), 
	"ENABLED" NUMBER(3,0) DEFAULT 1, 
	"PROTOCOL_O" VARCHAR2(45 BYTE), 
	"TRIAL" NUMBER(3,0) DEFAULT '1', 
	"SCXMLDOC_T" VARCHAR2(225 BYTE), 
	"PROTOCOL_T" VARCHAR2(45 BYTE), 
	"BPARTY_LENGTH" NUMBER(10,0), 
	"BPARTY_PREFIX" NUMBER(10,0), 
	"HASPREFIX" NUMBER(3,0), 
	"SSN" NUMBER(10,0) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;




--------------------------------------------------------
--  DDL for Table SIMULATIONS
--------------------------------------------------------

  CREATE TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" 
   (	"ID" NUMBER(10,0), 
	"CREATIONTIME" TIMESTAMP (0) DEFAULT SYSTIMESTAMP, 
	"SCHEDULEDTIME" TIMESTAMP (0), 
	"SPEEDFACTOR" NUMBER(10,0) DEFAULT NULL, 
	"DURATION" NUMBER(10,0) DEFAULT NULL, 
	"PROCESSEDTIME" TIMESTAMP (0) DEFAULT NULL, 
	"FINISHTIME" TIMESTAMP (0) DEFAULT NULL, 
	"ANUMBER" VARCHAR2(45 BYTE), 
	"BNUMBER" VARCHAR2(45 BYTE), 
	"USERNAME" VARCHAR2(45 BYTE), 
	"IDSTATUS" NUMBER(10,0), 
	"IDSCENARIOS" NUMBER(10,0), 
	"IDCCN" NUMBER(10,0), 
	"IDCOUNTRIES" NUMBER(10,0), 
	"IDLOCATION_NUMBERS" NUMBER(10,0), 
	"IDTRAFFIC_MODE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SIMULATIONS_STEPS
--------------------------------------------------------

  CREATE TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_STEPS" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(45 BYTE), 
	"DESCRIPTION" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"ICONPATH" VARCHAR2(45 BYTE), 
	"COLOR" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SIMULATIONS_SUMMARY
--------------------------------------------------------

  CREATE TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_SUMMARY" 
   (	"ID" NUMBER(10,0), 
	"ADDEDTIME" TIMESTAMP (3), 
	"EXTRAINFO" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"IDSIMULATION" NUMBER(10,0), 
	"IDSIMULATIONS_STEPS" NUMBER(10,0), 
	"IDANNOUNCEMENT" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STATUS
--------------------------------------------------------

  CREATE TABLE "TRAFFIC_SIMULATOR_SCHEMA"."STATUS" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(45 BYTE), 
	"ICONPATH" VARCHAR2(45 BYTE), 
	"COLOR" VARCHAR2(45 BYTE), 
	"DESCRIPTION" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TECHNICAL_FLOW
--------------------------------------------------------

  CREATE TABLE "TRAFFIC_SIMULATOR_SCHEMA"."TECHNICAL_FLOW" 
   (	"ID" NUMBER(10,0), 
	"ADDEDTIME" TIMESTAMP (3), 
	"MESSAGE" VARCHAR2(255 BYTE), 
	"IDSENDER" NUMBER(10,0), 
	"IDRECEIVER" NUMBER(10,0), 
	"IDSIMULATION" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRAFFIC_MODE
--------------------------------------------------------

  CREATE TABLE "TRAFFIC_SIMULATOR_SCHEMA"."TRAFFIC_MODE" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(45 BYTE) DEFAULT NULL, 
	"VALUE" VARCHAR2(45 BYTE), 
	"DESCRIPTION" VARCHAR2(45 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS_FOOTPRINTS
--------------------------------------------------------

  CREATE TABLE "TRAFFIC_SIMULATOR_SCHEMA"."USERS_FOOTPRINTS" 
   (	"ID" NUMBER(10,0), 
	"USERNAME" VARCHAR2(45 BYTE), 
	"LOGINTIME" TIMESTAMP (0), 
	"LOGOUTTIME" TIMESTAMP (0) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence ACTIVE_DIRECTORY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAFFIC_SIMULATOR_SCHEMA"."ACTIVE_DIRECTORY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 74 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CCN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAFFIC_SIMULATOR_SCHEMA"."CCN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 205 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COUNTRIES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAFFIC_SIMULATOR_SCHEMA"."COUNTRIES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LOCATION_NUMBERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAFFIC_SIMULATOR_SCHEMA"."LOCATION_NUMBERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 50 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence NODES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAFFIC_SIMULATOR_SCHEMA"."NODES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SCENARIOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAFFIC_SIMULATOR_SCHEMA"."SCENARIOS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 23 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SIMULATIONS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3022 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SIMULATIONS_STEPS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_STEPS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SIMULATIONS_SUMMARY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_SUMMARY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6683 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence STATUS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAFFIC_SIMULATOR_SCHEMA"."STATUS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TECHNICAL_FLOW_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAFFIC_SIMULATOR_SCHEMA"."TECHNICAL_FLOW_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6071 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRAFFIC_MODE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAFFIC_SIMULATOR_SCHEMA"."TRAFFIC_MODE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USERS_FOOTPRINTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAFFIC_SIMULATOR_SCHEMA"."USERS_FOOTPRINTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3341 CACHE 20 NOORDER  NOCYCLE ;

REM INSERTING into TRAFFIC_SIMULATOR_SCHEMA.ACTIVE_DIRECTORY
SET DEFINE OFF;
Insert into TRAFFIC_SIMULATOR_SCHEMA.ACTIVE_DIRECTORY (ID,SECURITY_PRINCIPAL,SECURITY_CREDENTIALS,SECURITY_AUTHENTICATION,PROVIDER_URL,DOMAIN,ACTIVE) values (55,null,null,'simple','ldap://10.230.96.225:389','vf-eg.internal.vodafone.com',1);
REM INSERTING into TRAFFIC_SIMULATOR_SCHEMA.ADMINS
SET DEFINE OFF;
Insert into TRAFFIC_SIMULATOR_SCHEMA.ADMINS (USERNAME,LDAP) values ('allaa',0);
Insert into TRAFFIC_SIMULATOR_SCHEMA.ADMINS (USERNAME,LDAP) values ('Samawal',0);
Insert into TRAFFIC_SIMULATOR_SCHEMA.ADMINS (USERNAME,LDAP) values ('edafa',0);
Insert into TRAFFIC_SIMULATOR_SCHEMA.ADMINS (USERNAME,LDAP) values ('admin',0);
Insert into TRAFFIC_SIMULATOR_SCHEMA.ADMINS (USERNAME,LDAP) values ('mohamed.elmorshedy',1);
Insert into TRAFFIC_SIMULATOR_SCHEMA.ADMINS (USERNAME,LDAP) values ('ayman.fathy',1);
Insert into TRAFFIC_SIMULATOR_SCHEMA.ADMINS (USERNAME,LDAP) values ('aya',0);
REM INSERTING into TRAFFIC_SIMULATOR_SCHEMA.ANNOUNCEMENT
SET DEFINE OFF;
Insert into TRAFFIC_SIMULATOR_SCHEMA.ANNOUNCEMENT (ID,NAME,PATH,ENABLED) values (6261,'Nafaz Sallefny','announcements/nafaz',1);
Insert into TRAFFIC_SIMULATOR_SCHEMA.ANNOUNCEMENT (ID,NAME,PATH,ENABLED) values (6262,'Nafaz Sallefny','announcements/nafaz',1);
Insert into TRAFFIC_SIMULATOR_SCHEMA.ANNOUNCEMENT (ID,NAME,PATH,ENABLED) values (6263,'Nafaz Sallefny','announcements/nafaz',1);
Insert into TRAFFIC_SIMULATOR_SCHEMA.ANNOUNCEMENT (ID,NAME,PATH,ENABLED) values (1620,'Rx_Awshak','announcements/low-balance',1);
Insert into TRAFFIC_SIMULATOR_SCHEMA.ANNOUNCEMENT (ID,NAME,PATH,ENABLED) values (1621,'Rx_Awshak','announcements/low-balance',1);
Insert into TRAFFIC_SIMULATOR_SCHEMA.ANNOUNCEMENT (ID,NAME,PATH,ENABLED) values (6007,'Rx_Awshak','announcements/low-balance',1);
Insert into TRAFFIC_SIMULATOR_SCHEMA.ANNOUNCEMENT (ID,NAME,PATH,ENABLED) values (6044,'Call Collect 3al Nota',' ',1);
Insert into TRAFFIC_SIMULATOR_SCHEMA.ANNOUNCEMENT (ID,NAME,PATH,ENABLED) values (6065,'Call Collect Nafaz',' ',1);
Insert into TRAFFIC_SIMULATOR_SCHEMA.ANNOUNCEMENT (ID,NAME,PATH,ENABLED) values (6066,'Call Collect Nafaz',' ',1);
Insert into TRAFFIC_SIMULATOR_SCHEMA.ANNOUNCEMENT (ID,NAME,PATH,ENABLED) values (6110,'Call Collect Nafaz',' ',1);
REM INSERTING into TRAFFIC_SIMULATOR_SCHEMA.CCN
SET DEFINE OFF;
Insert into TRAFFIC_SIMULATOR_SCHEMA.CCN (ID,NAME,PC,DESCRIPTION,ENABLED,DEFAULTVALUE) values (2,'OpenCloud',133,null,1,1);
Insert into TRAFFIC_SIMULATOR_SCHEMA.CCN (ID,NAME,PC,DESCRIPTION,ENABLED,DEFAULTVALUE) values (185,'ccn',5,'ccn',0,1);
REM INSERTING into TRAFFIC_SIMULATOR_SCHEMA.COUNTRIES
SET DEFINE OFF;
Insert into TRAFFIC_SIMULATOR_SCHEMA.COUNTRIES (ID,NAME,DESCRIPTION,ENABLED,MNC,MCC,DIAL_CODE,DEFAULTVALUE) values (1,'Saudi',null,1,'50','420','965',1);
Insert into TRAFFIC_SIMULATOR_SCHEMA.COUNTRIES (ID,NAME,DESCRIPTION,ENABLED,MNC,MCC,DIAL_CODE,DEFAULTVALUE) values (0,'Select ..',null,0,'1','1','99',0);
REM INSERTING into TRAFFIC_SIMULATOR_SCHEMA.ENGINE_CONFIGURATION
SET DEFINE OFF;
Insert into TRAFFIC_SIMULATOR_SCHEMA.ENGINE_CONFIGURATION (PC,SSN) values (482,9);
REM INSERTING into TRAFFIC_SIMULATOR_SCHEMA.LOCATION_NUMBERS
SET DEFINE OFF;
Insert into TRAFFIC_SIMULATOR_SCHEMA.LOCATION_NUMBERS (ID,NAME,VALUE,DESCRIPTION,ENABLED,DEFAULTVALUE) values (6,'Qebly','20165986000',null,1,1);
Insert into TRAFFIC_SIMULATOR_SCHEMA.LOCATION_NUMBERS (ID,NAME,VALUE,DESCRIPTION,ENABLED,DEFAULTVALUE) values (7,'Bahary','20165983000',null,1,1);
Insert into TRAFFIC_SIMULATOR_SCHEMA.LOCATION_NUMBERS (ID,NAME,VALUE,DESCRIPTION,ENABLED,DEFAULTVALUE) values (5,'Alex','20165982000',null,1,1);
Insert into TRAFFIC_SIMULATOR_SCHEMA.LOCATION_NUMBERS (ID,NAME,VALUE,DESCRIPTION,ENABLED,DEFAULTVALUE) values (0,'Select',' ',null,1,1);
Insert into TRAFFIC_SIMULATOR_SCHEMA.LOCATION_NUMBERS (ID,NAME,VALUE,DESCRIPTION,ENABLED,DEFAULTVALUE) values (9,'Test','123456',null,1,1);
Insert into TRAFFIC_SIMULATOR_SCHEMA.LOCATION_NUMBERS (ID,NAME,VALUE,DESCRIPTION,ENABLED,DEFAULTVALUE) values (49,'hahahha','4','hahahah',1,1);
REM INSERTING into TRAFFIC_SIMULATOR_SCHEMA.NODES
SET DEFINE OFF;
Insert into TRAFFIC_SIMULATOR_SCHEMA.NODES (ID,NAME,DESCRIPTION) values (1,'SIM',null);
Insert into TRAFFIC_SIMULATOR_SCHEMA.NODES (ID,NAME,DESCRIPTION) values (2,'CCN',null);
REM INSERTING into TRAFFIC_SIMULATOR_SCHEMA.SCENARIOS
SET DEFINE OFF;
Insert into TRAFFIC_SIMULATOR_SCHEMA.SCENARIOS (ID,NAME,SCXMLDOC_O,DESCRIPTION,HASCOUNTRY,HASTRAFFICMODE,HASLOCATIONNUMBERS,HASDURATION,SERVICEKEY_O,SERVICEKEY_T,ENABLED,PROTOCOL_O,TRIAL,SCXMLDOC_T,PROTOCOL_T,BPARTY_LENGTH,BPARTY_PREFIX,HASPREFIX,SSN) values (2,'SMS','file:///data/traffic-simulator/scenarios/sms-scenario.scxml',null,0,0,1,0,1890,1990,1,'ecs1p',0,'ter','ecs1p',0,0,0,252);
Insert into TRAFFIC_SIMULATOR_SCHEMA.SCENARIOS (ID,NAME,SCXMLDOC_O,DESCRIPTION,HASCOUNTRY,HASTRAFFICMODE,HASLOCATIONNUMBERS,HASDURATION,SERVICEKEY_O,SERVICEKEY_T,ENABLED,PROTOCOL_O,TRIAL,SCXMLDOC_T,PROTOCOL_T,BPARTY_LENGTH,BPARTY_PREFIX,HASPREFIX,SSN) values (12,'Edafa Demo','file:///data/traffic-simulator/scenarios/ecs1p-scenarios_demo01.scxml',null,0,0,1,1,1090,1190,1,'ecs1p',0,'file:///data/traffic-simulator/scenarios/ecs1p-scenarios.scxml','ecs1p',8,0,1,252);
Insert into TRAFFIC_SIMULATOR_SCHEMA.SCENARIOS (ID,NAME,SCXMLDOC_O,DESCRIPTION,HASCOUNTRY,HASTRAFFICMODE,HASLOCATIONNUMBERS,HASDURATION,SERVICEKEY_O,SERVICEKEY_T,ENABLED,PROTOCOL_O,TRIAL,SCXMLDOC_T,PROTOCOL_T,BPARTY_LENGTH,BPARTY_PREFIX,HASPREFIX,SSN) values (1,'Voice Local','file:///data/traffic-simulator/scenarios/ecs1p-scenarios.scxml',null,0,0,1,1,1090,1190,1,'ecs1p',0,'file:///data/traffic-simulator/scenarios/ecs1p-scenarios.scxml','ecs1p',8,0,1,252);
Insert into TRAFFIC_SIMULATOR_SCHEMA.SCENARIOS (ID,NAME,SCXMLDOC_O,DESCRIPTION,HASCOUNTRY,HASTRAFFICMODE,HASLOCATIONNUMBERS,HASDURATION,SERVICEKEY_O,SERVICEKEY_T,ENABLED,PROTOCOL_O,TRIAL,SCXMLDOC_T,PROTOCOL_T,BPARTY_LENGTH,BPARTY_PREFIX,HASPREFIX,SSN) values (5,'Voice Roaming','file:///data/traffic-simulator/scenarios/capv2-scenarios.scxml',null,1,1,0,1,1090,1190,1,'capv2',0,'file:///data/traffic-simulator/scenarios/ecs1p-scenarios.scxml','ecs1p',0,0,0,252);
REM INSERTING into TRAFFIC_SIMULATOR_SCHEMA.STATUS
SET DEFINE OFF;
Insert into TRAFFIC_SIMULATOR_SCHEMA.STATUS (ID,NAME,ICONPATH,COLOR,DESCRIPTION) values (1,'Succeeded','resources/images/right.png','#009900',null);
Insert into TRAFFIC_SIMULATOR_SCHEMA.STATUS (ID,NAME,ICONPATH,COLOR,DESCRIPTION) values (2,'Failed','resources/images/wrong.png','red',null);
Insert into TRAFFIC_SIMULATOR_SCHEMA.STATUS (ID,NAME,ICONPATH,COLOR,DESCRIPTION) values (3,'Pending','resources/images/schedualed.png','#f57900',null);
Insert into TRAFFIC_SIMULATOR_SCHEMA.STATUS (ID,NAME,ICONPATH,COLOR,DESCRIPTION) values (4,'Processing','resources/images/process.png','#666600',null);
Insert into TRAFFIC_SIMULATOR_SCHEMA.STATUS (ID,NAME,ICONPATH,COLOR,DESCRIPTION) values (5,'Invalid','resources/images/wrong.png','grey',null);
REM INSERTING into TRAFFIC_SIMULATOR_SCHEMA.TRAFFIC_MODE
SET DEFINE OFF;
Insert into TRAFFIC_SIMULATOR_SCHEMA.TRAFFIC_MODE (ID,NAME,VALUE,DESCRIPTION) values (1,'Originating','originating',null);
Insert into TRAFFIC_SIMULATOR_SCHEMA.TRAFFIC_MODE (ID,NAME,VALUE,DESCRIPTION) values (2,'Terminating','terminating',null);
--------------------------------------------------------
--  DDL for Index SYS_C0029508
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."SYS_C0029508" ON "TRAFFIC_SIMULATOR_SCHEMA"."ACTIVE_DIRECTORY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027186
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."SYS_C0027186" ON "TRAFFIC_SIMULATOR_SCHEMA"."ADMINS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027190
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."SYS_C0027190" ON "TRAFFIC_SIMULATOR_SCHEMA"."ANNOUNCEMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027195
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."SYS_C0027195" ON "TRAFFIC_SIMULATOR_SCHEMA"."CCN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027199
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."SYS_C0027199" ON "TRAFFIC_SIMULATOR_SCHEMA"."COUNTRIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027267
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."SYS_C0027267" ON "TRAFFIC_SIMULATOR_SCHEMA"."ENGINE_CONFIGURATION" ("PC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027203
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."SYS_C0027203" ON "TRAFFIC_SIMULATOR_SCHEMA"."LOCATION_NUMBERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027254
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."SYS_C0027254" ON "TRAFFIC_SIMULATOR_SCHEMA"."NODES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027211
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."SYS_C0027211" ON "TRAFFIC_SIMULATOR_SCHEMA"."SCENARIOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027228
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."SYS_C0027228" ON "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FK_SIM_CCN1_IDX
--------------------------------------------------------

  CREATE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."FK_SIM_CCN1_IDX" ON "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" ("IDCCN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FK_SIM_COUNTRIES1_IDX
--------------------------------------------------------

  CREATE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."FK_SIM_COUNTRIES1_IDX" ON "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" ("IDCOUNTRIES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FK_SIM_LOC_NUMBERS1_IDX
--------------------------------------------------------

  CREATE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."FK_SIM_LOC_NUMBERS1_IDX" ON "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" ("IDLOCATION_NUMBERS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FK_SIM_SCENARIOS1_IDX
--------------------------------------------------------

  CREATE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."FK_SIM_SCENARIOS1_IDX" ON "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" ("IDSCENARIOS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FK_SIM_STATUS_IDX
--------------------------------------------------------

  CREATE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."FK_SIM_STATUS_IDX" ON "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" ("IDSTATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FK_SIM_TRAFFIC_MODE1_IDX
--------------------------------------------------------

  CREATE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."FK_SIM_TRAFFIC_MODE1_IDX" ON "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" ("IDTRAFFIC_MODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027239
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."SYS_C0027239" ON "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_STEPS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027244
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."SYS_C0027244" ON "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_SUMMARY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FK_SIM_SUM_ANNOUNCEMENTS_IDX
--------------------------------------------------------

  CREATE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."FK_SIM_SUM_ANNOUNCEMENTS_IDX" ON "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_SUMMARY" ("IDANNOUNCEMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FK_SIM_SUM_SIMULATION1_IDX
--------------------------------------------------------

  CREATE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."FK_SIM_SUM_SIMULATION1_IDX" ON "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_SUMMARY" ("IDSIMULATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FK_SIM_SUM_SIM_STEPS1_IDX
--------------------------------------------------------

  CREATE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."FK_SIM_SUM_SIM_STEPS1_IDX" ON "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_SUMMARY" ("IDSIMULATIONS_STEPS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027219
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."SYS_C0027219" ON "TRAFFIC_SIMULATOR_SCHEMA"."STATUS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FK_TECHNICAL_SIMULATION_IDX
--------------------------------------------------------

  CREATE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."FK_TECHNICAL_SIMULATION_IDX" ON "TRAFFIC_SIMULATOR_SCHEMA"."TECHNICAL_FLOW" ("IDSIMULATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027261
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."SYS_C0027261" ON "TRAFFIC_SIMULATOR_SCHEMA"."TECHNICAL_FLOW" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FK_TECHNICAL_NODES1_IDX
--------------------------------------------------------

  CREATE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."FK_TECHNICAL_NODES1_IDX" ON "TRAFFIC_SIMULATOR_SCHEMA"."TECHNICAL_FLOW" ("IDSENDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FK_TECHNICAL_NODES2_IDX
--------------------------------------------------------

  CREATE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."FK_TECHNICAL_NODES2_IDX" ON "TRAFFIC_SIMULATOR_SCHEMA"."TECHNICAL_FLOW" ("IDRECEIVER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027214
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."SYS_C0027214" ON "TRAFFIC_SIMULATOR_SCHEMA"."TRAFFIC_MODE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0027251
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAFFIC_SIMULATOR_SCHEMA"."SYS_C0027251" ON "TRAFFIC_SIMULATOR_SCHEMA"."USERS_FOOTPRINTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ACTIVE_DIRECTORY
--------------------------------------------------------

  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."ACTIVE_DIRECTORY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."ACTIVE_DIRECTORY" MODIFY ("SECURITY_AUTHENTICATION" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."ACTIVE_DIRECTORY" MODIFY ("PROVIDER_URL" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."ACTIVE_DIRECTORY" MODIFY ("DOMAIN" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."ACTIVE_DIRECTORY" MODIFY ("ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."ACTIVE_DIRECTORY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMINS
--------------------------------------------------------

  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."ADMINS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."ADMINS" ADD PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ANNOUNCEMENT
--------------------------------------------------------

  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."ANNOUNCEMENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."ANNOUNCEMENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."ANNOUNCEMENT" MODIFY ("PATH" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."ANNOUNCEMENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CCN
--------------------------------------------------------

  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."CCN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."CCN" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."CCN" MODIFY ("PC" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."CCN" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COUNTRIES
--------------------------------------------------------

  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."COUNTRIES" MODIFY ("MCC" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."COUNTRIES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."COUNTRIES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."COUNTRIES" MODIFY ("MNC" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."COUNTRIES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ENGINE_CONFIGURATION
--------------------------------------------------------

  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."ENGINE_CONFIGURATION" MODIFY ("PC" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."ENGINE_CONFIGURATION" MODIFY ("SSN" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."ENGINE_CONFIGURATION" ADD PRIMARY KEY ("PC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCATION_NUMBERS
--------------------------------------------------------

  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."LOCATION_NUMBERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."LOCATION_NUMBERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."LOCATION_NUMBERS" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."LOCATION_NUMBERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NODES
--------------------------------------------------------

  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."NODES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."NODES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."NODES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SCENARIOS
--------------------------------------------------------

  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SCENARIOS" MODIFY ("PROTOCOL_O" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SCENARIOS" MODIFY ("SCXMLDOC_T" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SCENARIOS" MODIFY ("PROTOCOL_T" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SCENARIOS" MODIFY ("SSN" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SCENARIOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SCENARIOS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SCENARIOS" MODIFY ("SCXMLDOC_O" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SCENARIOS" MODIFY ("HASCOUNTRY" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SCENARIOS" MODIFY ("HASTRAFFICMODE" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SCENARIOS" MODIFY ("HASLOCATIONNUMBERS" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SCENARIOS" MODIFY ("HASDURATION" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SCENARIOS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SIMULATIONS
--------------------------------------------------------

  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" MODIFY ("CREATIONTIME" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" MODIFY ("SCHEDULEDTIME" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" MODIFY ("ANUMBER" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" MODIFY ("BNUMBER" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" MODIFY ("IDSCENARIOS" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" MODIFY ("IDCCN" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SIMULATIONS_STEPS
--------------------------------------------------------

  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_STEPS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_STEPS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_STEPS" MODIFY ("ICONPATH" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_STEPS" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_STEPS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SIMULATIONS_SUMMARY
--------------------------------------------------------

  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_SUMMARY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_SUMMARY" MODIFY ("ADDEDTIME" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_SUMMARY" MODIFY ("IDSIMULATION" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_SUMMARY" MODIFY ("IDSIMULATIONS_STEPS" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_SUMMARY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATUS
--------------------------------------------------------

  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."STATUS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."STATUS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."STATUS" MODIFY ("ICONPATH" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."STATUS" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."STATUS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TECHNICAL_FLOW
--------------------------------------------------------

  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."TECHNICAL_FLOW" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."TECHNICAL_FLOW" MODIFY ("ADDEDTIME" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."TECHNICAL_FLOW" MODIFY ("MESSAGE" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."TECHNICAL_FLOW" MODIFY ("IDSENDER" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."TECHNICAL_FLOW" MODIFY ("IDRECEIVER" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."TECHNICAL_FLOW" MODIFY ("IDSIMULATION" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."TECHNICAL_FLOW" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRAFFIC_MODE
--------------------------------------------------------

  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."TRAFFIC_MODE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."TRAFFIC_MODE" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."TRAFFIC_MODE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS_FOOTPRINTS
--------------------------------------------------------

  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."USERS_FOOTPRINTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."USERS_FOOTPRINTS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."USERS_FOOTPRINTS" MODIFY ("LOGINTIME" NOT NULL ENABLE);
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."USERS_FOOTPRINTS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SIMULATIONS
--------------------------------------------------------

  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" ADD CONSTRAINT "FK_SIMULATION_CCN1" FOREIGN KEY ("IDCCN")
	  REFERENCES "TRAFFIC_SIMULATOR_SCHEMA"."CCN" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" ADD CONSTRAINT "FK_SIMULATION_COUNTRIES1" FOREIGN KEY ("IDCOUNTRIES")
	  REFERENCES "TRAFFIC_SIMULATOR_SCHEMA"."COUNTRIES" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" ADD CONSTRAINT "FK_SIMULATION_LOC_NUMBERS1" FOREIGN KEY ("IDLOCATION_NUMBERS")
	  REFERENCES "TRAFFIC_SIMULATOR_SCHEMA"."LOCATION_NUMBERS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" ADD CONSTRAINT "FK_SIMULATION_SCENARIOS1" FOREIGN KEY ("IDSCENARIOS")
	  REFERENCES "TRAFFIC_SIMULATOR_SCHEMA"."SCENARIOS" ("ID") ENABLE;
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" ADD CONSTRAINT "FK_SIMULATION_STATUS" FOREIGN KEY ("IDSTATUS")
	  REFERENCES "TRAFFIC_SIMULATOR_SCHEMA"."STATUS" ("ID") ENABLE;
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" ADD CONSTRAINT "FK_SIMULATION_TRAFFIC_MODE1" FOREIGN KEY ("IDTRAFFIC_MODE")
	  REFERENCES "TRAFFIC_SIMULATOR_SCHEMA"."TRAFFIC_MODE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SIMULATIONS_SUMMARY
--------------------------------------------------------

  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_SUMMARY" ADD CONSTRAINT "FK_SIM_SUM_ANNOUNCEMENTS" FOREIGN KEY ("IDANNOUNCEMENT")
	  REFERENCES "TRAFFIC_SIMULATOR_SCHEMA"."ANNOUNCEMENT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_SUMMARY" ADD CONSTRAINT "FK_SIM_SUM_SIMULATION1" FOREIGN KEY ("IDSIMULATION")
	  REFERENCES "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_SUMMARY" ADD CONSTRAINT "FK_SIM_SUM_SIMULATIONS_STEPS1" FOREIGN KEY ("IDSIMULATIONS_STEPS")
	  REFERENCES "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_STEPS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TECHNICAL_FLOW
--------------------------------------------------------

  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."TECHNICAL_FLOW" ADD CONSTRAINT "FK_TECHNICAL_FLOW_RECEIVER" FOREIGN KEY ("IDRECEIVER")
	  REFERENCES "TRAFFIC_SIMULATOR_SCHEMA"."NODES" ("ID") ENABLE;
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."TECHNICAL_FLOW" ADD CONSTRAINT "FK_TECHNICAL_FLOW_SENDER" FOREIGN KEY ("IDSENDER")
	  REFERENCES "TRAFFIC_SIMULATOR_SCHEMA"."NODES" ("ID") ENABLE;
  ALTER TABLE "TRAFFIC_SIMULATOR_SCHEMA"."TECHNICAL_FLOW" ADD CONSTRAINT "FK_TECHNICAL_FLOW_SIMULATIONS" FOREIGN KEY ("IDSIMULATION")
	  REFERENCES "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  DDL for Trigger ACTIVE_DIRECTORY_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."ACTIVE_DIRECTORY_SEQ_TR" 
 BEFORE INSERT ON traffic_simulator_schema.ACTIVE_DIRECTORY FOR EACH ROW
    WHEN (NEW.ID IS NULL) BEGIN
 SELECT traffic_simulator_schema.ACTIVE_DIRECTORY_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
ALTER TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."ACTIVE_DIRECTORY_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CCN_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."CCN_SEQ_TR" 
 BEFORE INSERT ON traffic_simulator_schema.ccn FOR EACH ROW
   WHEN (NEW.id IS NULL) BEGIN
 SELECT traffic_simulator_schema.ccn_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."CCN_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COUNTRIES_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."COUNTRIES_SEQ_TR" 
 BEFORE INSERT ON traffic_simulator_schema.countries FOR EACH ROW
   WHEN (NEW.id IS NULL) BEGIN
 SELECT traffic_simulator_schema.countries_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."COUNTRIES_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOCATION_NUMBERS_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."LOCATION_NUMBERS_SEQ_TR" 
 BEFORE INSERT ON traffic_simulator_schema.location_numbers FOR EACH ROW
   WHEN (NEW.id IS NULL) BEGIN
 SELECT traffic_simulator_schema.location_numbers_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."LOCATION_NUMBERS_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NODES_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."NODES_SEQ_TR" 
 BEFORE INSERT ON traffic_simulator_schema.nodes FOR EACH ROW
   WHEN (NEW.id IS NULL) BEGIN
 SELECT traffic_simulator_schema.nodes_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."NODES_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SCENARIOS_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."SCENARIOS_SEQ_TR" 
 BEFORE INSERT ON traffic_simulator_schema.scenarios FOR EACH ROW
   WHEN (NEW.id IS NULL) BEGIN
 SELECT traffic_simulator_schema.scenarios_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."SCENARIOS_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SIMULATIONS_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_SEQ_TR" 
 BEFORE INSERT ON traffic_simulator_schema.simulations FOR EACH ROW
   WHEN (NEW.id IS NULL) BEGIN
 SELECT traffic_simulator_schema.simulations_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SIMULATIONS_STEPS_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_STEPS_SEQ_TR" 
 BEFORE INSERT ON traffic_simulator_schema.simulations_steps FOR EACH ROW
   WHEN (NEW.id IS NULL) BEGIN
 SELECT traffic_simulator_schema.simulations_steps_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_STEPS_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SIMULATIONS_SUMMARY_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_SUMMARY_SEQ_TR" 
 BEFORE INSERT ON traffic_simulator_schema.simulations_summary FOR EACH ROW
   WHEN (NEW.id IS NULL) BEGIN
 SELECT traffic_simulator_schema.simulations_summary_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."SIMULATIONS_SUMMARY_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STATUS_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."STATUS_SEQ_TR" 
 BEFORE INSERT ON traffic_simulator_schema.status FOR EACH ROW
   WHEN (NEW.id IS NULL) BEGIN
 SELECT traffic_simulator_schema.status_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."STATUS_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TECHNICAL_FLOW_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."TECHNICAL_FLOW_SEQ_TR" 
 BEFORE INSERT ON traffic_simulator_schema.technical_flow FOR EACH ROW
   WHEN (NEW.id IS NULL) BEGIN
 SELECT traffic_simulator_schema.technical_flow_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."TECHNICAL_FLOW_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRAFFIC_MODE_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."TRAFFIC_MODE_SEQ_TR" 
 BEFORE INSERT ON traffic_simulator_schema.traffic_mode FOR EACH ROW
   WHEN (NEW.id IS NULL) BEGIN
 SELECT traffic_simulator_schema.traffic_mode_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."TRAFFIC_MODE_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USERS_FOOTPRINTS_SEQ_TR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."USERS_FOOTPRINTS_SEQ_TR" 
 BEFORE INSERT ON traffic_simulator_schema.users_footprints FOR EACH ROW
   WHEN (NEW.id IS NULL) BEGIN
 SELECT traffic_simulator_schema.users_footprints_seq.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/
ALTER TRIGGER "TRAFFIC_SIMULATOR_SCHEMA"."USERS_FOOTPRINTS_SEQ_TR" ENABLE;
--------------------------------------------------------
--  DDL for Procedure HOUSEKEEPINGPROCEDURE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "TRAFFIC_SIMULATOR_SCHEMA"."HOUSEKEEPINGPROCEDURE" AS
BEGIN
      delete from simulations_summary where simulations_summary.idSimulation in
			(select id from simulations where  simulations.creationTime < CURRENT_TIMESTAMP - INTERVAL '3' MONTH);

      delete from technical_flow where technical_flow.idSimulation in
			(select id from simulations where  simulations.creationTime < CURRENT_TIMESTAMP - INTERVAL '3' MONTH);

      delete from simulations where simulations.creationTime < CURRENT_TIMESTAMP - INTERVAL '3' MONTH;

	  delete from ccn
			where enabled=0 and id not in (select DISTINCT idCCN  from simulations);

	  delete from countries
			where enabled=0 and id not in (select DISTINCT idCountries  from simulations);

      delete from location_numbers
			where enabled=0 and id not in (select DISTINCT idLocation_Numbers  from simulations);

      delete from announcement
			where enabled=0 and id not in (select DISTINCT idAnnouncement  from simulations_summary);
commit;
END HouseKeepingProcedure;

/


exit;



