--------------------------------------------------------
--  File created - Wednesday-March-20-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WEBCLIENTPOOL
--------------------------------------------------------
CONNECT SCHEDULER_SCHEMA/scheduler_12345@//localhost:1521/TRAFFIC_SIMULATOR;

  CREATE TABLE "SCHEDULER_SCHEMA"."WEBCLIENTPOOL" 
   (	"KEY" VARCHAR2(50 BYTE), 
	"VALUE" VARCHAR2(45 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SCHEDULER_SCHEMA.WEBCLIENTPOOL
SET DEFINE OFF;
Insert into SCHEDULER_SCHEMA.WEBCLIENTPOOL (KEY,VALUE) values ('accept','text/html');
Insert into SCHEDULER_SCHEMA.WEBCLIENTPOOL (KEY,VALUE) values ('connectionNumbers','10');
Insert into SCHEDULER_SCHEMA.WEBCLIENTPOOL (KEY,VALUE) values ('connectionRequestTimeout','3000');
Insert into SCHEDULER_SCHEMA.WEBCLIENTPOOL (KEY,VALUE) values ('connectionTimeout','3000');
Insert into SCHEDULER_SCHEMA.WEBCLIENTPOOL (KEY,VALUE) values ('duration','6000');
Insert into SCHEDULER_SCHEMA.WEBCLIENTPOOL (KEY,VALUE) values ('hostName','127.0.0.1');
Insert into SCHEDULER_SCHEMA.WEBCLIENTPOOL (KEY,VALUE) values ('methodType','GET');
Insert into SCHEDULER_SCHEMA.WEBCLIENTPOOL (KEY,VALUE) values ('path','/restcomm');
Insert into SCHEDULER_SCHEMA.WEBCLIENTPOOL (KEY,VALUE) values ('port','9090');
Insert into SCHEDULER_SCHEMA.WEBCLIENTPOOL (KEY,VALUE) values ('secured','0');
Insert into SCHEDULER_SCHEMA.WEBCLIENTPOOL (KEY,VALUE) values ('socketTimeOut','3000');
--------------------------------------------------------
--  DDL for Index SYS_C0026275
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHEDULER_SCHEMA"."SYS_C0026275" ON "SCHEDULER_SCHEMA"."WEBCLIENTPOOL" ("KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table WEBCLIENTPOOL
--------------------------------------------------------

  ALTER TABLE "SCHEDULER_SCHEMA"."WEBCLIENTPOOL" MODIFY ("KEY" NOT NULL ENABLE);
  ALTER TABLE "SCHEDULER_SCHEMA"."WEBCLIENTPOOL" ADD PRIMARY KEY ("KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;


exit;
